# Generated by Django 5.0.6 on 2024-06-26 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('payer', models.CharField(max_length=255)),
                ('membership_number', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=255)),
                ('validity', models.CharField(max_length=255)),
                ('scheme', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Discharged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('payer', models.CharField(max_length=255)),
                ('membership_number', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=255)),
                ('validity', models.CharField(max_length=255)),
                ('scheme', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Member_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('membership_number', models.CharField(max_length=100)),
                ('payer', models.CharField(max_length=100)),
                ('scheme', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('validity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MemberDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('payer', models.CharField(max_length=255)),
                ('membership_number', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=255)),
                ('validity', models.CharField(max_length=255)),
                ('scheme', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_type', models.CharField(max_length=100)),
                ('cover_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_details', to='dashed.member_detail')),
            ],
        ),
    ]
