# Generated by Django 5.0.6 on 2024-07-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discharge',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='discharged',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
