# Generated by Django 5.0.6 on 2024-07-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0002_discharge_added_at_discharged_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_detail',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
