# Generated by Django 5.0.6 on 2024-07-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0003_member_detail_added_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schemes', models.ManyToManyField(related_name='providers', to='dashed.scheme')),
            ],
        ),
    ]
