# Generated by Django 5.0.6 on 2024-07-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0004_scheme_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='schemes',
        ),
        migrations.AddField(
            model_name='scheme',
            name='providers',
            field=models.ManyToManyField(related_name='schemes', to='dashed.provider'),
        ),
    ]
