# Generated by Django 5.0.6 on 2024-07-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0005_remove_provider_schemes_scheme_providers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='providers',
        ),
        migrations.AddField(
            model_name='provider',
            name='schemes',
            field=models.ManyToManyField(related_name='providers', to='dashed.scheme'),
        ),
    ]
