# Generated by Django 5.0.6 on 2024-07-24 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0006_remove_scheme_providers_provider_schemes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField()),
                ('admission_diagnosis', models.CharField(max_length=100)),
                ('cover_used', models.CharField(max_length=100)),
                ('initial_cover_value', models.CharField(max_length=100)),
                ('initial_cover_balance', models.CharField(max_length=100)),
                ('requested_amount', models.CharField(max_length=100)),
                ('lou_issued', models.CharField(max_length=100)),
                ('admited_by', models.CharField(max_length=100)),
                ('Provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_details', to='dashed.provider')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_details', to='dashed.member_detail')),
            ],
        ),
    ]
