# Generated by Django 5.0.6 on 2024-07-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0007_admission_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_detail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('admitted', 'Admitted'), ('discharged', 'Discharged')], default='pending', max_length=20),
        ),
    ]
