# Generated by Django 5.0.6 on 2024-07-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0009_member_detail_admission_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_detail',
            name='added_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
