# Generated by Django 5.0.6 on 2024-08-04 11:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0011_alter_member_detail_added_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discharge_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=100)),
                ('membership_number', models.CharField(max_length=100)),
                ('payer', models.CharField(max_length=100)),
                ('scheme', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('validity', models.CharField(max_length=100)),
                ('admission_status', models.CharField(choices=[('pending', 'Pending'), ('admitted', 'Admitted'), ('discharged', 'Discharged')], default='pending', max_length=20)),
                ('admission_date', models.DateField()),
                ('admission_diagnosis', models.CharField(max_length=100)),
                ('cover_used', models.CharField(max_length=100)),
                ('initial_cover_value', models.CharField(max_length=100)),
                ('initial_cover_balance', models.CharField(max_length=100)),
                ('requested_amount', models.CharField(max_length=100)),
                ('lou_issued', models.CharField(max_length=100)),
                ('admitted_by', models.CharField(max_length=100)),
                ('discharge_date', models.DateField(default=django.utils.timezone.now)),
                ('discharge_summary', models.TextField()),
                ('final_cover_balance', models.CharField(max_length=100)),
                ('days_admitted', models.PositiveIntegerField(default=0)),
                ('discharge_notes', models.TextField()),
                ('discharged_by', models.CharField(max_length=100)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discharge_details', to='dashed.member_detail')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discharge_details', to='dashed.provider')),
            ],
        ),
    ]
