# Generated by Django 5.0.6 on 2024-08-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0012_discharge_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discharge_details',
            name='admission_status',
        ),
    ]
