# Generated by Django 5.0.6 on 2024-08-04 13:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0013_remove_discharge_details_admission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('progress_notes', models.TextField()),
                ('interim_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='dashed.admission_details')),
            ],
        ),
    ]
