# Generated by Django 5.0.6 on 2024-08-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0014_daily_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_update',
            name='care_manager',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
