# Generated by Django 5.0.6 on 2024-08-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0015_daily_update_care_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discharge_details',
            old_name='final_cover_balance',
            new_name='final_approved_amount',
        ),
    ]
