# Generated by Django 5.0.6 on 2024-08-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0016_rename_final_cover_balance_discharge_details_final_approved_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discharge',
        ),
        migrations.DeleteModel(
            name='Discharged',
        ),
        migrations.DeleteModel(
            name='MemberDetail',
        ),
    ]
