# Generated by Django 5.0.6 on 2024-08-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0017_delete_discharge_delete_discharged_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discharge_details',
            name='member',
        ),
        migrations.AlterField(
            model_name='discharge_details',
            name='provider',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
