# Generated by Django 5.0.6 on 2024-08-09 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0018_remove_discharge_details_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discharge_details',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discharge_details', to='dashed.member_detail'),
        ),
    ]
