# Generated by Django 5.0.6 on 2024-08-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0019_discharge_details_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discharge_details',
            name='discharge_summary',
        ),
        migrations.RemoveField(
            model_name='discharge_details',
            name='member',
        ),
    ]
