# Generated by Django 5.0.6 on 2024-09-01 20:38

import dashed.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0020_remove_discharge_details_discharge_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='agreed_packages',
            field=models.FileField(null=True, upload_to='agreed_packages/', validators=[django.core.validators.FileExtensionValidator(['.csv', '.xlsx', '.xls', '.pdf']), dashed.models.validate_file_mimetype]),
        ),
        migrations.AddField(
            model_name='provider',
            name='care_manager',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='cm_contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='services',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='payer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='policy_document',
            field=models.FileField(null=True, upload_to='policy_documents/', validators=[django.core.validators.FileExtensionValidator(['.csv', '.xlsx', '.xls', '.pdf']), dashed.models.validate_file_mimetype]),
        ),
        migrations.AddField(
            model_name='scheme',
            name='policy_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='policy_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='rm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='rm_contact',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
