# Generated by Django 5.0.6 on 2024-11-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0021_provider_agreed_packages_provider_care_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_update',
            name='interim_bill',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
