# Generated by Django 5.0.6 on 2024-11-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0022_alter_daily_update_interim_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission_details',
            name='lou_issued',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='discharge_details',
            name='final_approved_amount',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
