# Generated by Django 5.0.6 on 2024-11-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0023_alter_admission_details_lou_issued_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discharge_details',
            name='days_admitted',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='discharge_details',
            name='final_approved_amount',
            field=models.CharField(max_length=100),
        ),
    ]
