# Generated by Django 5.0.6 on 2024-11-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0024_alter_discharge_details_days_admitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discharge_details',
            name='final_approved_amount',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
