# Generated by Django 5.0.6 on 2024-11-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0026_alter_discharge_details_final_approved_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='policy_document',
        ),
    ]
