# Generated by Django 5.0.6 on 2024-11-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0030_delete_payer_delete_providerpanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='service_provider',
            field=models.ManyToManyField(blank=True, related_name='scheme', to='dashed.provider'),
        ),
    ]
