# Generated by Django 5.0.6 on 2024-11-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0031_scheme_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='provider_notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='scheme_notes',
            field=models.TextField(null=True),
        ),
    ]
