# Generated by Django 5.0.6 on 2024-11-27 13:10

import dashed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0032_provider_provider_notes_scheme_scheme_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='agreed_packages',
            field=models.FileField(null=True, upload_to='agreed_packages/', validators=[dashed.models.validate_file_mimetype]),
        ),
    ]
