# Generated by Django 5.0.6 on 2024-11-29 11:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0033_provider_agreed_packages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_manager_update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update', models.TextField()),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
