# Generated by Django 5.0.6 on 2024-12-03 07:54

import dashed.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashed', '0034_case_manager_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='policy_document',
            field=models.FileField(null=True, upload_to='policy_documents/', validators=[django.core.validators.FileExtensionValidator(['.csv', '.xlsx', '.xls', '.pdf']), dashed.models.validate_file_mimetype]),
        ),
    ]
