# Generated by Django 5.0.6 on 2024-06-03 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(max_length=255)),
                ('membership_number', models.CharField(max_length=255, unique=True)),
                ('relationship', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('validity', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('scheme', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_type', models.CharField(max_length=255)),
                ('cover_value', models.CharField(max_length=255)),
                ('cover_balance', models.CharField(max_length=255)),
                ('membership_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.memberdetail')),
            ],
        ),
        migrations.AlterField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.memberdetail'),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
